INSERT INTO users(id, identification, name, username, password) VALUES (1, '10512582', 'Manuel', 'Manu98', '12345');
INSERT INTO users(id, identification, name, username, password) VALUES (2, '2544521', 'Salome', 'Salome98', '12345');
INSERT INTO users(id, identification, name, username, password) VALUES (3, '354544', 'Maria', 'Maria98', '12345');

INSERT INTO products(id, identification, name, ammount, price, applyVariants, description, img) VALUES (1, '001', 'Chaleco de peso 40LBS', 500, 134900, false, 'Chaleco de peso para realizar rutinas de entrenamiento de alta y media intensidad, cuenta con compartimientos a cada lado (delantero y trasero) en los cuales se encuentran las tulas de peso para graduarlo al deseado.\nMaterial: Lona de tráfico pesado\n\nCuenta con 8 compartimientos\n\nIncluye 16 bolsas de peso, cada una de 1.250 gramos para un total de 20 kilos (40 Lbs)\n\nPRODUCTO NACIONAL\nMedidas:\nLargo:34 cm\nAlto:33 cm\nAncho:13 cm', 'images/products/chalecoPeso/imageOne.JPG');
INSERT INTO products(id, identification, name, ammount, price, applyVariants, description, img) VALUES (2, '002', 'Termo', 20, 50000, false, 'Description', 'images/products/tendedero/imageOne.png,images/products/tendedero/imageThree.png,images/products/tendedero/imageTwo.png');
INSERT INTO products(id, identification, name, ammount, price, applyVariants, description, img) VALUES (3, '003', 'Tablero', 150, 15000, false, 'Description', 'images/products/tendedero/imageOne.png,images/products/tendedero/imageThree.png,images/products/tendedero/imageTwo.png');
INSERT INTO products(id, identification, name, ammount, price, applyVariants, description, img) VALUES (4, '004', 'Cafetera', 5, 200000, false, 'Description', 'images/products/tendedero/imageOne.png,images/products/tendedero/imageThree.png,images/products/tendedero/imageTwo.png');
INSERT INTO products(id, identification, name, ammount, price, applyVariants, description, img) VALUES (5, '005', 'Termo', 20, 50000, false, 'Description', 'images/products/tendedero/imageOne.png,images/products/tendedero/imageThree.png,images/products/tendedero/imageTwo.png');
INSERT INTO products(id, identification, name, ammount, price, applyVariants, description, img) VALUES (6, '006', 'Tablero', 150, 15000, false, 'Description', 'images/products/tendedero/imageOne.png,images/products/tendedero/imageThree.png,images/products/tendedero/imageTwo.png');